version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - .tmp/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: django_pg