# Generated by Django 3.2.6 on 2021-08-03 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="letter_set",
                related_query_name="letter",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="letter",
            unique_together={("title", "content")},
        ),
    ]
