# Generated by Django 3.2.6 on 2021-08-10 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=256, unique=True, verbose_name="이메일"),
            preserve_default=False,
        ),
    ]
